version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/local.db:/app/local.db  # Mounta SQLite för persistens

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    # Volym för utveckling kan läggas till vid behov
    environment:
      - NODE_ENV=production
