version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tradingbot}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tradingpass}
      POSTGRES_DB: ${POSTGRES_DB:-tradingbot}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: