# Fokusera på viktiga kodfiler
focus:
  - "backend/strategies/**/*.py"
  - "backend/services/**/*.py"
  - "backend/routes/**/*.py"
  - "src/components/**/*.tsx"
  - "src/hooks/**/*.ts"

# Ignorera testdata och konfigurationsfiler
ignore:
  - "**/*.json"
  - "**/*.yml"
  - "**/*.yaml"
  - "**/tests/data/**"
  - "**/.env*"
  - "**/node_modules/**"
  - "**/venv/**"
  - "**/.codex_backups/**" 